# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 18:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_minutes', models.IntegerField()),
                ('environment', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
