# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActuatorVariableModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField(unique=True)),
                ("json", jsonfield.fields.JSONField()),
            ],
            options={
                "verbose_name": "Actuator Variable",
                "verbose_name_plural": "Actuator Variables",
            },
        ),
        migrations.CreateModel(
            name="ConnectModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json", jsonfield.fields.JSONField()),
            ],
            options={"verbose_name": "Connect", "verbose_name_plural": "Connects"},
        ),
        migrations.CreateModel(
            name="ControllerSetupModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.TextField()),
                ("json", jsonfield.fields.JSONField()),
            ],
            options={
                "verbose_name": "Controller Setup",
                "verbose_name_plural": "Controller Setups",
            },
        ),
        migrations.CreateModel(
            name="CultivarModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.TextField()),
                ("json", jsonfield.fields.JSONField()),
            ],
            options={"verbose_name": "Cultivar", "verbose_name_plural": "Cultivars"},
        ),
        migrations.CreateModel(
            name="CultivationMethodModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.TextField()),
                ("json", jsonfield.fields.JSONField()),
            ],
            options={
                "verbose_name": "Cultivation Method",
                "verbose_name_plural": "Cultivation Methods",
            },
        ),
        migrations.CreateModel(
            name="DeviceConfigModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.TextField()),
                ("json", jsonfield.fields.JSONField()),
            ],
            options={
                "verbose_name": "Device Configuration",
                "verbose_name_plural": "Device Configurations",
            },
        ),
        migrations.CreateModel(
            name="EnvironmentModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("state", jsonfield.fields.JSONField()),
            ],
            options={
                "verbose_name": "Environment",
                "verbose_name_plural": "Environments",
                "get_latest_by": "timestamp",
            },
        ),
        migrations.CreateModel(
            name="EventModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("recipient", jsonfield.fields.JSONField()),
                ("request", jsonfield.fields.JSONField()),
                ("response", jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "get_latest_by": "timestamp",
            },
        ),
        migrations.CreateModel(
            name="IoTConfigModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_config_version", models.IntegerField()),
            ],
            options={
                "verbose_name": "IoTConfig",
                "verbose_name_plural": "IoTConfigs",
                "get_latest_by": "last_config_version",
            },
        ),
        migrations.CreateModel(
            name="PeripheralSetupModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.TextField()),
                ("json", jsonfield.fields.JSONField()),
            ],
            options={
                "verbose_name": "Peripheral Setup",
                "verbose_name_plural": "Peripheral Setups",
            },
        ),
        migrations.CreateModel(
            name="RecipeModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("json", jsonfield.fields.JSONField()),
                ("name", models.TextField()),
                ("version", models.TextField()),
            ],
            options={"verbose_name": "Recipe", "verbose_name_plural": "Recipes"},
        ),
        migrations.CreateModel(
            name="RecipeTransitionModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minute", models.IntegerField()),
                ("phase", models.TextField()),
                ("cycle", models.TextField()),
                ("environment_name", models.TextField()),
                ("environment_state", jsonfield.fields.JSONField()),
            ],
            options={
                "verbose_name": "Recipe Transition",
                "verbose_name_plural": "Recipe Transitions",
            },
        ),
        migrations.CreateModel(
            name="SensorVariableModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField(unique=True)),
                ("json", jsonfield.fields.JSONField()),
            ],
            options={
                "verbose_name": "Sensor Variable",
                "verbose_name_plural": "Sensor Variables",
            },
        ),
        migrations.CreateModel(
            name="StateModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("device", jsonfield.fields.JSONField()),
                ("recipe", jsonfield.fields.JSONField()),
                ("environment", jsonfield.fields.JSONField()),
                ("peripherals", jsonfield.fields.JSONField()),
                ("controllers", jsonfield.fields.JSONField()),
                ("iot", jsonfield.fields.JSONField()),
                ("resource", jsonfield.fields.JSONField()),
                ("connect", jsonfield.fields.JSONField()),
                ("upgrade", jsonfield.fields.JSONField()),
            ],
            options={"verbose_name": "State", "verbose_name_plural": "States"},
        ),
    ]
