# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsedrecipe',
            old_name='timestamp_minutes',
            new_name='minute',
        ),
        migrations.AddField(
            model_name='parsedrecipe',
            name='phase',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
