# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 14:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='recipient',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'name': None, 'type': 'Device'}),
            preserve_default=False,
        ),
    ]
