# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeripheralConfigModel',
            new_name='PeripheralSetupModel',
        ),
        migrations.AlterModelOptions(
            name='peripheralsetupmodel',
            options={'verbose_name': 'Peripheral Setup', 'verbose_name_plural': 'Peripheral Setup'},
        ),
    ]
