# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180324_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParsedRecipe',
            new_name='RecipeTransition',
        ),
    ]
