# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-14 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0003_iotconfigmodel")]

    operations = [
        migrations.RemoveField(model_name="deviceconfigmodel", name="version")
    ]
