# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 11:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0004_remove_deviceconfigmodel_version")]

    operations = [
        migrations.AddField(
            model_name="statemodel",
            name="iot",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=""),
            preserve_default=False,
        )
    ]
