# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 15:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_statemodel_iot'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemodel',
            name='resource',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
