# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 22:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180324_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('recipe_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('system_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('recipe_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('peripheral_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('controller_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('log_summary', models.TextField()),
            ],
        ),
    ]
