# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-06 13:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_statemodel_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemodel',
            name='connect',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
