# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 18:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_device_environment_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('device', django.contrib.postgres.fields.jsonb.JSONField()),
                ('recipe', django.contrib.postgres.fields.jsonb.JSONField()),
                ('environment', django.contrib.postgres.fields.jsonb.JSONField()),
                ('peripherals', django.contrib.postgres.fields.jsonb.JSONField()),
                ('controllers', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
