# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 19:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180828_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemodel',
            name='upgrade',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
