# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 21:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_statemodel_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerSetupModel',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Controller Setup',
                'verbose_name_plural': 'Controller Setups',
            },
        ),
    ]
