# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 20:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
