# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='timestamp',
        ),
    ]
