# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180328_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
