# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-01 23:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180328_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('guid', models.CharField(blank=True, max_length=40, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'State'},
        ),
    ]
