# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180401_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='json',
            new_name='recipe_json',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='guid',
        ),
        migrations.AddField(
            model_name='recipe',
            name='uuid',
            field=models.UUIDField(default=None, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
