# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 22:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180402_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
