# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_environment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
