# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 21:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180402_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfigModel',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Device Config',
                'verbose_name_plural': 'Device Configs',
            },
        ),
    ]
