# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_deviceconfigmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceConfigModel',
            new_name='DeviceConfigurationModel',
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='EventModel',
        ),
        migrations.AlterModelOptions(
            name='deviceconfigurationmodel',
            options={'verbose_name': 'Device Configuration', 'verbose_name_plural': 'Device Configurations'},
        ),
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'get_latest_by': 'timestamp', 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
