WHOIS_PING = "Ping"
SET_TEST_V = "Test"
SET_AIR_TEMP = "Air Temp"
SET_AIR_RH = "Air RH"

# unused below
LOCAL_AIR_TEMP = "Local Air Temp"
LOCAL_AIR_RH = "Local Air RH"
TEMP_SEL = "Temp Selection"
RH_SEL = "Humidity Selection"
REMOTE_TEMP_AVG = "Remote Temp Avg"
REMOTE_RH_AVG = "Remote Humidity Avg"
TEMP_1_IN = "Temp 1 Input"
TEMP_2_IN = "Temp 2 Input"
TEMP_3_IN = "Temp 3 Input"
TEMP_4_IN = "Temp 4 Input"
TEMP_5_IN = "Temp 5 Input"
TEMP_1_VAL = "Temp 1 Value"
TEMP_2_VAL = "Temp 2 Value"
TEMP_3_VAL = "Temp 3 Value"
TEMP_4_VAL = "Temp 4 Value"
TEMP_5_VAL = "Temp 5 Value"
USE_TEMP_1 = "Use Temp 1"
USE_TEMP_2 = "Use Temp 2"
USE_TEMP_3 = "Use Temp 3"
USE_TEMP_4 = "Use Temp 4"
USE_TEMP_5 = "Use Temp 5"
